import components.simplereader.SimpleReader;
import components.simplereader.SimpleReader1L;
import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;
import components.xmltree.XMLTree;
import components.xmltree.XMLTree1;

/**
 * Program to convert an XML RSS (version 2.0) feed from a given URL into the
 * corresponding HTML output file.
 *
 * @author Cameron Erdman
 *
 */
public final class RSSReader {

    /**
     * Private constructor so this utility class cannot be instantiated.
     */
    private RSSReader() {
    }

    /**
     * Outputs the "opening" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * <html> <head> <title>the channel tag title as the page title</title>
     * </head> <body>
     * <h1>the page title inside a link to the <channel> link</h1>
     * <p>
     * the channel description
     * </p>
     * <table border="1">
     * <tr>
     * <th>Date</th>
     * <th>Source</th>
     * <th>News</th>
     * </tr>
     *
     * @param channel
     *            the channel element XMLTree
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the root of channel is a <channel> tag] and out.is_open
     * @ensures out.content = #out.content * [the HTML "opening" tags]
     */
    private static void outputHeader(XMLTree channel, SimpleWriter out) {
        assert channel != null : "Violation of: channel is not null";
        assert out != null : "Violation of: out is not null";
        assert channel.isTag() && channel.label().equals("channel") : ""
                + "Violation of: the label root of channel is a <channel> tag";
        assert out.isOpen() : "Violation of: out.is_open";

//finds the channel and prints the associated required tags
        int channelID = getChildElement(channel, "title");
        if (channelID != -1) {
            out.println("<html> <head> <title> "
                    + channel.child(channelID).child(0).label() + "</title>");
        } else {
            out.println("<html> <head> <title> Empty Title </title>");
        }
        out.println("</head> <body>");
//finds the link to the news site and prints the tags with it
        int linkID = getChildElement(channel, "link");
        out.println("<h1> <a href= \"" + channel.child(linkID).child(0).label()
                + "\"> " + channel.child(channelID).child(0).label()
                + " </a></h1>");
//prints the description as well as the remaining tags
        int descriptionID = getChildElement(channel, "description");
        if (descriptionID != -1) {
            out.println("<p>" + channel.child(descriptionID).child(0).label()
                    + "</p>");
        } else {
            out.println("<p> No Description </p>");
        }
        out.println("<table border=\"1\">");
        out.println("<tr>");
        out.println("<th>Date</th>");
        out.println("<th>Source</th>");
        out.println("<th>News</th>");
        out.println("</tr>");
    }

    /**
     * Outputs the "closing" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * </table>
     * </body> </html>
     *
     * @param out
     *            the output stream
     * @updates out.contents
     * @requires out.is_open
     * @ensures out.content = #out.content * [the HTML "closing" tags]
     */
    private static void outputFooter(SimpleWriter out) {
        assert out != null : "Violation of: out is not null";
        assert out.isOpen() : "Violation of: out.is_open";
        //prints the closing tags
        out.println("</table>");
        out.println("</body> </html>");
    }

    /**
     * Finds the first occurrence of the given tag among the children of the
     * given {@code XMLTree} and return its index; returns -1 if not found.
     *
     * @param xml
     *            the {@code XMLTree} to search
     * @param tag
     *            the tag to look for
     * @return the index of the first child of type tag of the {@code XMLTree}
     *         or -1 if not found
     * @requires [the label of the root of xml is a tag]
     * @ensures <pre>
     * getChildElement =
     *  [the index of the first child of type tag of the {@code XMLTree} or
     *   -1 if not found]
     * </pre>
     */
    private static int getChildElement(XMLTree xml, String tag) {
        assert xml != null : "Violation of: xml is not null";
        assert tag != null : "Violation of: tag is not null";
        assert xml.isTag() : "Violation of: the label root of xml is a tag";

        int ret = -1; //sets return value to -1 incase the child isn't found
        int i = 0;
        //loops until the tag is found or no more children to search
        while (ret < 0 && i < xml.numberOfChildren()) {
            String name = xml.child(i).label();
            if (tag.equals(name)) { //if childs tag equals the searched for tag
                ret = i; //set ret to the index of that child
            }
            i++;
        }

        return ret; //returns the index of the first child with tag
    }

    /**
     * Processes one news item and outputs one table row. The row contains three
     * elements: the publication date, the source, and the title (or
     * description) of the item.
     *
     * @param item
     *            the news item
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the label of the root of item is an <item> tag] and
     *           out.is_open
     * @ensures <pre>
     * out.content = #out.content *
     *   [an HTML table row with publication date, source, and title of news item]
     * </pre>
     */
    private static void processItem(XMLTree item, SimpleWriter out) {
        assert item != null : "Violation of: item is not null";
        assert out != null : "Violation of: out is not null";
        assert item.isTag() && item.label().equals("item") : ""
                + "Violation of: the label root of item is an <item> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        out.println("<tr>");
        int linkID = getChildElement(item, "link");
        int pubID = getChildElement(item, "pubDate");
        //if pub ID could be found prints it, else print no date available
        if (pubID != -1) {
            out.println("<td>" + item.child(pubID).child(0).label() + "</td>");
        } else {
            out.println("<td> No date available </td>");
        }

        int sourceID = getChildElement(item, "source");
        //prints the source id if it coulf be found, else print no source available
        if (sourceID != -1) {
            out.println("<td> <a href = \""
                    + item.child(sourceID).attributeValue("url") + "\">"
                    + item.child(sourceID).child(0).label() + "</a> </td>");
        } else {
            out.println("<td> No Source Available </td>");
        }
        //various checks to determine which to print
        int titleID = getChildElement(item, "title");
        int descriptionID = getChildElement(item, "description");
        //if the title is available print it
        if (titleID != -1 && !item.child(titleID).child(0).isTag()) {
            out.println("<td> <a href = \""
                    + item.child(linkID).child(0).label() + "\">"
                    + item.child(titleID).child(0).label() + "</a> </td>");
            //else print the description if its available
        } else if (descriptionID != -1
                && !item.child(descriptionID).child(0).isTag()) {
            out.println(
                    "<td> <a href = \"" + item.child(linkID).child(0).label()
                            + "\">" + item.child(descriptionID).child(0).label()
                            + "</a> </td>");
            //else print only the link if it is available and no title or description
        } else if (linkID != -1) {
            out.println(
                    "<td> <a href = \"" + item.child(linkID).child(0).label()
                            + "> No title available </a> </td>");
            //else print no title available
        } else {
            out.println("<td> No title available </td>");
        }
        out.println("</tr>");

    }

    /**
     * Asks for an rss link and checks to ensure it is a valid version 2.0 and
     * returns the xml item if it is.
     *
     * @param in
     *            the input stream
     *
     * @param out
     *            the output stream
     *
     * @return returns a valid xml item
     */
    private static XMLTree checkRSS(SimpleReader in, SimpleWriter out) {
        int x = 0;
        XMLTree xml = null;
        while (x != 1) {
            out.print("Enter the name of the RSS link: "); //https://news.yahoo.com/rss/
            String rss = in.nextLine();
            xml = new XMLTree1(rss); //grabs the tree and cheks if its rss 2.0
            if (xml.isTag() && xml.label().equals("rss")
                    && xml.hasAttribute("version")
                    && xml.attributeValue("version").equals("2.0")) {
                x = 1;
            } else {
                out.println("Sorry, this is not a valid rss link");
            }
        } //loops until a valid link is provided and returns it
        return xml;
    }

    /**
     * Main method.
     *
     * @param args
     *            the command line arguments; unused here
     */
    public static void main(String[] args) {
        SimpleReader in = new SimpleReader1L();
        SimpleWriter out = new SimpleWriter1L();

        XMLTree xml = checkRSS(in, out);

        out.print("Enter an output file, make sure to include the .html: "); //index.html
        String html = in.nextLine();
        SimpleWriter htmlOut = new SimpleWriter1L(html);

        outputHeader(xml.child(0), htmlOut);
        //loops from first case of item to last
        for (int i = getChildElement(xml.child(0), "item"); i < xml.child(0)
                .numberOfChildren(); i++) {
            processItem(xml.child(0).child(i), htmlOut);
        }
        outputFooter(htmlOut);

        in.close();
        out.close();
        htmlOut.close();
    }

}
